name: ci 
on:
  push:
    branches:
      - ci_test 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: mkdir ~/docs
      - run: mv * ~/docs
      - run: mkdir docs
      - run: mv ~/docs ./docs
      - run: ls -la
      - run: pwd
      - run: mv docs/.git .
      - run: git clone https://github.com/karpovilia/mkdocs_template.git
      - run: rm -rf mkdocs_template/.git/
      - run: rm -rf mkdocs_template/docs/
      - run: mv mkdocs_template/* .
      - run: rm -rf mkdocs_template/
      - run: ls -la
      - run: ls -la docs
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
